# Generated by Django 5.2.1 on 2025-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='firebase_uid',
            field=models.CharField(default=0.00018518518518518518, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
